// Указывает версию Protocol Buffers. syntax = "proto3" означает использование

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: api/bot/bot.proto

// Определяет пространство имен пакета для protobuf. Это имя будет использоваться
// в сгенерированном коде как префикс для всех сообщений и сервисов.
// Позволяет избежать конфликтов имен между разными .proto файлами

package bot

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Запрос на обработку обновления от Telegram
type UpdateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Числа 1,2,3 - это теги полей, используемые для бинарной сериализации.
	// Они должны быть уникальными в рамках сообщения и не меняться между версиями
	UpdateId      int64          `protobuf:"varint,1,opt,name=update_id,json=updateId,proto3" json:"update_id,omitempty"`               // Уникальный ID обновления от Telegram API.
	Message       *Message       `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`                                  // Сообщение от пользователя (опционально, может отсутствовать)
	CallbackQuery *CallbackQuery `protobuf:"bytes,3,opt,name=callback_query,json=callbackQuery,proto3" json:"callback_query,omitempty"` // Callback запрос от inline клавиатуры (опционально)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_api_bot_bot_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_bot_bot_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_api_bot_bot_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateRequest) GetUpdateId() int64 {
	if x != nil {
		return x.UpdateId
	}
	return 0
}

func (x *UpdateRequest) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *UpdateRequest) GetCallbackQuery() *CallbackQuery {
	if x != nil {
		return x.CallbackQuery
	}
	return nil
}

// Представляет сообщение от пользователя в Telegram
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     int64                  `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"` // Уникальный ID сообщения в чате
	ChatId        int64                  `protobuf:"varint,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`          // ID чата (может быть личным, групповым и т.д.)
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`          // ID пользователя, отправившего сообщение
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`                             // Текст сообщения
	Date          int64                  `protobuf:"varint,5,opt,name=date,proto3" json:"date,omitempty"`                            // Unix timestamp отправки сообщения
	From          *User                  `protobuf:"bytes,6,opt,name=from,proto3" json:"from,omitempty"`                             // Информация об отправителе
	Chat          *Chat                  `protobuf:"bytes,7,opt,name=chat,proto3" json:"chat,omitempty"`                             // Информация о чате
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_api_bot_bot_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_api_bot_bot_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_api_bot_bot_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *Message) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *Message) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Message) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Message) GetDate() int64 {
	if x != nil {
		return x.Date
	}
	return 0
}

func (x *Message) GetFrom() *User {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *Message) GetChat() *Chat {
	if x != nil {
		return x.Chat
	}
	return nil
}

// Представляет callback запрос от inline клавиатуры
// Когда пользователь нажимает кнопку с callback_data, приходит такой запрос
type CallbackQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                 // Уникальный ID callback запроса
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`          // ID пользователя, нажавшего кнопку
	MessageId     int64                  `protobuf:"varint,3,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"` // ID сообщения с клавиатурой
	ChatId        int64                  `protobuf:"varint,4,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`          // ID чата, где находится сообщение
	Data          string                 `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`                             // Данные, связанные с кнопкой (callback_data)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallbackQuery) Reset() {
	*x = CallbackQuery{}
	mi := &file_api_bot_bot_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallbackQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallbackQuery) ProtoMessage() {}

func (x *CallbackQuery) ProtoReflect() protoreflect.Message {
	mi := &file_api_bot_bot_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallbackQuery.ProtoReflect.Descriptor instead.
func (*CallbackQuery) Descriptor() ([]byte, []int) {
	return file_api_bot_bot_proto_rawDescGZIP(), []int{2}
}

func (x *CallbackQuery) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CallbackQuery) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CallbackQuery) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *CallbackQuery) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *CallbackQuery) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// Информация о пользователе Telegram
type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                               // Уникальный ID пользователя
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"` // Имя пользователя
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`    // Фамилия (опционально)
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`                    // Username (опционально, без @)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_api_bot_bot_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_api_bot_bot_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_api_bot_bot_proto_rawDescGZIP(), []int{3}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *User) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *User) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

// Информация о чате Telegram
type Chat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`      // Уникальный ID чата
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`   // Тип чата: "private", "group", "supergroup", "channel"
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"` // Название чата (для групп и каналов)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chat) Reset() {
	*x = Chat{}
	mi := &file_api_bot_bot_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chat) ProtoMessage() {}

func (x *Chat) ProtoReflect() protoreflect.Message {
	mi := &file_api_bot_bot_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chat.ProtoReflect.Descriptor instead.
func (*Chat) Descriptor() ([]byte, []int) {
	return file_api_bot_bot_proto_rawDescGZIP(), []int{4}
}

func (x *Chat) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Chat) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Chat) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

// Ответ на обработку обновления
type UpdateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`  // Успешно ли обработано обновление
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`       // Текст ошибки (если success = false)
	Messages      []*OutgoingMessage     `protobuf:"bytes,3,rep,name=messages,proto3" json:"messages,omitempty"` // Сообщения для отправки (repeated = массив/слайс)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_api_bot_bot_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_bot_bot_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_api_bot_bot_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *UpdateResponse) GetMessages() []*OutgoingMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

// Исходящее сообщение от бота
type OutgoingMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`               // ID чата для отправки
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`                                  // Текст сообщения
	ReplyMarkup   *ReplyMarkup           `protobuf:"bytes,3,opt,name=reply_markup,json=replyMarkup,proto3" json:"reply_markup,omitempty"` // Клавиатура (опционально)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutgoingMessage) Reset() {
	*x = OutgoingMessage{}
	mi := &file_api_bot_bot_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutgoingMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutgoingMessage) ProtoMessage() {}

func (x *OutgoingMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_bot_bot_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutgoingMessage.ProtoReflect.Descriptor instead.
func (*OutgoingMessage) Descriptor() ([]byte, []int) {
	return file_api_bot_bot_proto_rawDescGZIP(), []int{6}
}

func (x *OutgoingMessage) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *OutgoingMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *OutgoingMessage) GetReplyMarkup() *ReplyMarkup {
	if x != nil {
		return x.ReplyMarkup
	}
	return nil
}

// Разметка ответа (клавиатура). Использует oneof для указания одного из типов
type ReplyMarkup struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// oneof означает, что может быть только одно из полей
	//
	// Types that are valid to be assigned to Type:
	//
	//	*ReplyMarkup_InlineKeyboard
	//	*ReplyMarkup_ReplyKeyboard
	Type          isReplyMarkup_Type `protobuf_oneof:"type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyMarkup) Reset() {
	*x = ReplyMarkup{}
	mi := &file_api_bot_bot_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyMarkup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyMarkup) ProtoMessage() {}

func (x *ReplyMarkup) ProtoReflect() protoreflect.Message {
	mi := &file_api_bot_bot_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyMarkup.ProtoReflect.Descriptor instead.
func (*ReplyMarkup) Descriptor() ([]byte, []int) {
	return file_api_bot_bot_proto_rawDescGZIP(), []int{7}
}

func (x *ReplyMarkup) GetType() isReplyMarkup_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *ReplyMarkup) GetInlineKeyboard() *InlineKeyboardMarkup {
	if x != nil {
		if x, ok := x.Type.(*ReplyMarkup_InlineKeyboard); ok {
			return x.InlineKeyboard
		}
	}
	return nil
}

func (x *ReplyMarkup) GetReplyKeyboard() *ReplyKeyboardMarkup {
	if x != nil {
		if x, ok := x.Type.(*ReplyMarkup_ReplyKeyboard); ok {
			return x.ReplyKeyboard
		}
	}
	return nil
}

type isReplyMarkup_Type interface {
	isReplyMarkup_Type()
}

type ReplyMarkup_InlineKeyboard struct {
	InlineKeyboard *InlineKeyboardMarkup `protobuf:"bytes,1,opt,name=inline_keyboard,json=inlineKeyboard,proto3,oneof"` // Inline клавиатура (под сообщением)
}

type ReplyMarkup_ReplyKeyboard struct {
	ReplyKeyboard *ReplyKeyboardMarkup `protobuf:"bytes,2,opt,name=reply_keyboard,json=replyKeyboard,proto3,oneof"` // Обычная клавиатура (вместо поля ввода)
}

func (*ReplyMarkup_InlineKeyboard) isReplyMarkup_Type() {}

func (*ReplyMarkup_ReplyKeyboard) isReplyMarkup_Type() {}

// Inline клавиатура (кнопки под сообщением)
type InlineKeyboardMarkup struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*InlineKeyboardRow   `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"` // Массив рядов кнопок
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InlineKeyboardMarkup) Reset() {
	*x = InlineKeyboardMarkup{}
	mi := &file_api_bot_bot_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InlineKeyboardMarkup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InlineKeyboardMarkup) ProtoMessage() {}

func (x *InlineKeyboardMarkup) ProtoReflect() protoreflect.Message {
	mi := &file_api_bot_bot_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InlineKeyboardMarkup.ProtoReflect.Descriptor instead.
func (*InlineKeyboardMarkup) Descriptor() ([]byte, []int) {
	return file_api_bot_bot_proto_rawDescGZIP(), []int{8}
}

func (x *InlineKeyboardMarkup) GetRows() []*InlineKeyboardRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

// Ряд кнопок в inline клавиатуре
type InlineKeyboardRow struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Buttons       []*InlineKeyboardButton `protobuf:"bytes,1,rep,name=buttons,proto3" json:"buttons,omitempty"` // Кнопки в ряду
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InlineKeyboardRow) Reset() {
	*x = InlineKeyboardRow{}
	mi := &file_api_bot_bot_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InlineKeyboardRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InlineKeyboardRow) ProtoMessage() {}

func (x *InlineKeyboardRow) ProtoReflect() protoreflect.Message {
	mi := &file_api_bot_bot_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InlineKeyboardRow.ProtoReflect.Descriptor instead.
func (*InlineKeyboardRow) Descriptor() ([]byte, []int) {
	return file_api_bot_bot_proto_rawDescGZIP(), []int{9}
}

func (x *InlineKeyboardRow) GetButtons() []*InlineKeyboardButton {
	if x != nil {
		return x.Buttons
	}
	return nil
}

// Кнопка inline клавиатуры
type InlineKeyboardButton struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`                                     // Текст на кнопке
	CallbackData  string                 `protobuf:"bytes,2,opt,name=callback_data,json=callbackData,proto3" json:"callback_data,omitempty"` // Данные, которые придут в callback_query при нажатии
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`                                       // URL для открытия (если указан, callback_data игнорируется)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InlineKeyboardButton) Reset() {
	*x = InlineKeyboardButton{}
	mi := &file_api_bot_bot_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InlineKeyboardButton) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InlineKeyboardButton) ProtoMessage() {}

func (x *InlineKeyboardButton) ProtoReflect() protoreflect.Message {
	mi := &file_api_bot_bot_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InlineKeyboardButton.ProtoReflect.Descriptor instead.
func (*InlineKeyboardButton) Descriptor() ([]byte, []int) {
	return file_api_bot_bot_proto_rawDescGZIP(), []int{10}
}

func (x *InlineKeyboardButton) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *InlineKeyboardButton) GetCallbackData() string {
	if x != nil {
		return x.CallbackData
	}
	return ""
}

func (x *InlineKeyboardButton) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// Обычная клавиатура (заменяет поле ввода)
type ReplyKeyboardMarkup struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Rows            []*ReplyKeyboardRow    `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`                                                 // Ряды кнопок
	ResizeKeyboard  bool                   `protobuf:"varint,2,opt,name=resize_keyboard,json=resizeKeyboard,proto3" json:"resize_keyboard,omitempty"`      // Автоматически подгонять размер клавиатуры
	OneTimeKeyboard bool                   `protobuf:"varint,3,opt,name=one_time_keyboard,json=oneTimeKeyboard,proto3" json:"one_time_keyboard,omitempty"` // Скрыть клавиатуру после использования
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ReplyKeyboardMarkup) Reset() {
	*x = ReplyKeyboardMarkup{}
	mi := &file_api_bot_bot_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyKeyboardMarkup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyKeyboardMarkup) ProtoMessage() {}

func (x *ReplyKeyboardMarkup) ProtoReflect() protoreflect.Message {
	mi := &file_api_bot_bot_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyKeyboardMarkup.ProtoReflect.Descriptor instead.
func (*ReplyKeyboardMarkup) Descriptor() ([]byte, []int) {
	return file_api_bot_bot_proto_rawDescGZIP(), []int{11}
}

func (x *ReplyKeyboardMarkup) GetRows() []*ReplyKeyboardRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *ReplyKeyboardMarkup) GetResizeKeyboard() bool {
	if x != nil {
		return x.ResizeKeyboard
	}
	return false
}

func (x *ReplyKeyboardMarkup) GetOneTimeKeyboard() bool {
	if x != nil {
		return x.OneTimeKeyboard
	}
	return false
}

// Ряд кнопок в обычной клавиатуре
type ReplyKeyboardRow struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Buttons       []*ReplyKeyboardButton `protobuf:"bytes,1,rep,name=buttons,proto3" json:"buttons,omitempty"` // Кнопки в ряду
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyKeyboardRow) Reset() {
	*x = ReplyKeyboardRow{}
	mi := &file_api_bot_bot_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyKeyboardRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyKeyboardRow) ProtoMessage() {}

func (x *ReplyKeyboardRow) ProtoReflect() protoreflect.Message {
	mi := &file_api_bot_bot_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyKeyboardRow.ProtoReflect.Descriptor instead.
func (*ReplyKeyboardRow) Descriptor() ([]byte, []int) {
	return file_api_bot_bot_proto_rawDescGZIP(), []int{12}
}

func (x *ReplyKeyboardRow) GetButtons() []*ReplyKeyboardButton {
	if x != nil {
		return x.Buttons
	}
	return nil
}

// Кнопка обычной клавиатуры
type ReplyKeyboardButton struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"` // Текст на кнопке (отправится как сообщение при нажатии)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplyKeyboardButton) Reset() {
	*x = ReplyKeyboardButton{}
	mi := &file_api_bot_bot_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplyKeyboardButton) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplyKeyboardButton) ProtoMessage() {}

func (x *ReplyKeyboardButton) ProtoReflect() protoreflect.Message {
	mi := &file_api_bot_bot_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplyKeyboardButton.ProtoReflect.Descriptor instead.
func (*ReplyKeyboardButton) Descriptor() ([]byte, []int) {
	return file_api_bot_bot_proto_rawDescGZIP(), []int{13}
}

func (x *ReplyKeyboardButton) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// Запрос на отправку сообщения от бота
type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        int64                  `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`               // ID чата для отправки
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`                                  // Текст сообщения
	ReplyMarkup   *ReplyMarkup           `protobuf:"bytes,3,opt,name=reply_markup,json=replyMarkup,proto3" json:"reply_markup,omitempty"` // Клавиатура (опционально)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_api_bot_bot_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_bot_bot_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_api_bot_bot_proto_rawDescGZIP(), []int{14}
}

func (x *SendMessageRequest) GetChatId() int64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *SendMessageRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *SendMessageRequest) GetReplyMarkup() *ReplyMarkup {
	if x != nil {
		return x.ReplyMarkup
	}
	return nil
}

// Ответ на запрос отправки сообщения
type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // Успешно ли отправлено сообщение
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`      // Текст ошибки (если success = false)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_api_bot_bot_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_bot_bot_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_api_bot_bot_proto_rawDescGZIP(), []int{15}
}

func (x *SendMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendMessageResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_api_bot_bot_proto protoreflect.FileDescriptor

const file_api_bot_bot_proto_rawDesc = "" +
	"\n" +
	"\x11api/bot/bot.proto\x12\x03bot\"\x8f\x01\n" +
	"\rUpdateRequest\x12\x1b\n" +
	"\tupdate_id\x18\x01 \x01(\x03R\bupdateId\x12&\n" +
	"\amessage\x18\x02 \x01(\v2\f.bot.MessageR\amessage\x129\n" +
	"\x0ecallback_query\x18\x03 \x01(\v2\x12.bot.CallbackQueryR\rcallbackQuery\"\xc0\x01\n" +
	"\aMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\x12\x17\n" +
	"\achat_id\x18\x02 \x01(\x03R\x06chatId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12\x12\n" +
	"\x04date\x18\x05 \x01(\x03R\x04date\x12\x1d\n" +
	"\x04from\x18\x06 \x01(\v2\t.bot.UserR\x04from\x12\x1d\n" +
	"\x04chat\x18\a \x01(\v2\t.bot.ChatR\x04chat\"\x84\x01\n" +
	"\rCallbackQuery\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x03 \x01(\x03R\tmessageId\x12\x17\n" +
	"\achat_id\x18\x04 \x01(\x03R\x06chatId\x12\x12\n" +
	"\x04data\x18\x05 \x01(\tR\x04data\"n\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\"@\n" +
	"\x04Chat\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\"r\n" +
	"\x0eUpdateResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\x120\n" +
	"\bmessages\x18\x03 \x03(\v2\x14.bot.OutgoingMessageR\bmessages\"s\n" +
	"\x0fOutgoingMessage\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x123\n" +
	"\freply_markup\x18\x03 \x01(\v2\x10.bot.ReplyMarkupR\vreplyMarkup\"\x9e\x01\n" +
	"\vReplyMarkup\x12D\n" +
	"\x0finline_keyboard\x18\x01 \x01(\v2\x19.bot.InlineKeyboardMarkupH\x00R\x0einlineKeyboard\x12A\n" +
	"\x0ereply_keyboard\x18\x02 \x01(\v2\x18.bot.ReplyKeyboardMarkupH\x00R\rreplyKeyboardB\x06\n" +
	"\x04type\"B\n" +
	"\x14InlineKeyboardMarkup\x12*\n" +
	"\x04rows\x18\x01 \x03(\v2\x16.bot.InlineKeyboardRowR\x04rows\"H\n" +
	"\x11InlineKeyboardRow\x123\n" +
	"\abuttons\x18\x01 \x03(\v2\x19.bot.InlineKeyboardButtonR\abuttons\"a\n" +
	"\x14InlineKeyboardButton\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12#\n" +
	"\rcallback_data\x18\x02 \x01(\tR\fcallbackData\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\"\x95\x01\n" +
	"\x13ReplyKeyboardMarkup\x12)\n" +
	"\x04rows\x18\x01 \x03(\v2\x15.bot.ReplyKeyboardRowR\x04rows\x12'\n" +
	"\x0fresize_keyboard\x18\x02 \x01(\bR\x0eresizeKeyboard\x12*\n" +
	"\x11one_time_keyboard\x18\x03 \x01(\bR\x0foneTimeKeyboard\"F\n" +
	"\x10ReplyKeyboardRow\x122\n" +
	"\abuttons\x18\x01 \x03(\v2\x18.bot.ReplyKeyboardButtonR\abuttons\")\n" +
	"\x13ReplyKeyboardButton\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\"v\n" +
	"\x12SendMessageRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\x03R\x06chatId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x123\n" +
	"\freply_markup\x18\x03 \x01(\v2\x10.bot.ReplyMarkupR\vreplyMarkup\"E\n" +
	"\x13SendMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\x88\x01\n" +
	"\n" +
	"BotService\x128\n" +
	"\rProcessUpdate\x12\x12.bot.UpdateRequest\x1a\x13.bot.UpdateResponse\x12@\n" +
	"\vSendMessage\x12\x17.bot.SendMessageRequest\x1a\x18.bot.SendMessageResponseB)Z'bizhelper_v_1_20/global_models/grpc/botb\x06proto3"

var (
	file_api_bot_bot_proto_rawDescOnce sync.Once
	file_api_bot_bot_proto_rawDescData []byte
)

func file_api_bot_bot_proto_rawDescGZIP() []byte {
	file_api_bot_bot_proto_rawDescOnce.Do(func() {
		file_api_bot_bot_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_bot_bot_proto_rawDesc), len(file_api_bot_bot_proto_rawDesc)))
	})
	return file_api_bot_bot_proto_rawDescData
}

var file_api_bot_bot_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_api_bot_bot_proto_goTypes = []any{
	(*UpdateRequest)(nil),        // 0: bot.UpdateRequest
	(*Message)(nil),              // 1: bot.Message
	(*CallbackQuery)(nil),        // 2: bot.CallbackQuery
	(*User)(nil),                 // 3: bot.User
	(*Chat)(nil),                 // 4: bot.Chat
	(*UpdateResponse)(nil),       // 5: bot.UpdateResponse
	(*OutgoingMessage)(nil),      // 6: bot.OutgoingMessage
	(*ReplyMarkup)(nil),          // 7: bot.ReplyMarkup
	(*InlineKeyboardMarkup)(nil), // 8: bot.InlineKeyboardMarkup
	(*InlineKeyboardRow)(nil),    // 9: bot.InlineKeyboardRow
	(*InlineKeyboardButton)(nil), // 10: bot.InlineKeyboardButton
	(*ReplyKeyboardMarkup)(nil),  // 11: bot.ReplyKeyboardMarkup
	(*ReplyKeyboardRow)(nil),     // 12: bot.ReplyKeyboardRow
	(*ReplyKeyboardButton)(nil),  // 13: bot.ReplyKeyboardButton
	(*SendMessageRequest)(nil),   // 14: bot.SendMessageRequest
	(*SendMessageResponse)(nil),  // 15: bot.SendMessageResponse
}
var file_api_bot_bot_proto_depIdxs = []int32{
	1,  // 0: bot.UpdateRequest.message:type_name -> bot.Message
	2,  // 1: bot.UpdateRequest.callback_query:type_name -> bot.CallbackQuery
	3,  // 2: bot.Message.from:type_name -> bot.User
	4,  // 3: bot.Message.chat:type_name -> bot.Chat
	6,  // 4: bot.UpdateResponse.messages:type_name -> bot.OutgoingMessage
	7,  // 5: bot.OutgoingMessage.reply_markup:type_name -> bot.ReplyMarkup
	8,  // 6: bot.ReplyMarkup.inline_keyboard:type_name -> bot.InlineKeyboardMarkup
	11, // 7: bot.ReplyMarkup.reply_keyboard:type_name -> bot.ReplyKeyboardMarkup
	9,  // 8: bot.InlineKeyboardMarkup.rows:type_name -> bot.InlineKeyboardRow
	10, // 9: bot.InlineKeyboardRow.buttons:type_name -> bot.InlineKeyboardButton
	12, // 10: bot.ReplyKeyboardMarkup.rows:type_name -> bot.ReplyKeyboardRow
	13, // 11: bot.ReplyKeyboardRow.buttons:type_name -> bot.ReplyKeyboardButton
	7,  // 12: bot.SendMessageRequest.reply_markup:type_name -> bot.ReplyMarkup
	0,  // 13: bot.BotService.ProcessUpdate:input_type -> bot.UpdateRequest
	14, // 14: bot.BotService.SendMessage:input_type -> bot.SendMessageRequest
	5,  // 15: bot.BotService.ProcessUpdate:output_type -> bot.UpdateResponse
	15, // 16: bot.BotService.SendMessage:output_type -> bot.SendMessageResponse
	15, // [15:17] is the sub-list for method output_type
	13, // [13:15] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_api_bot_bot_proto_init() }
func file_api_bot_bot_proto_init() {
	if File_api_bot_bot_proto != nil {
		return
	}
	file_api_bot_bot_proto_msgTypes[7].OneofWrappers = []any{
		(*ReplyMarkup_InlineKeyboard)(nil),
		(*ReplyMarkup_ReplyKeyboard)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_bot_bot_proto_rawDesc), len(file_api_bot_bot_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_bot_bot_proto_goTypes,
		DependencyIndexes: file_api_bot_bot_proto_depIdxs,
		MessageInfos:      file_api_bot_bot_proto_msgTypes,
	}.Build()
	File_api_bot_bot_proto = out.File
	file_api_bot_bot_proto_goTypes = nil
	file_api_bot_bot_proto_depIdxs = nil
}
